FROM mcr.microsoft.com/dotnet/sdk:5.0-buster-slim as build
WORKDIR /app
EXPOSE 80
COPY Gateway/Gateways/Course.Gateway/*.csproj Gateway/Gateways/Course.Gateway/


RUN dotnet restore Gateway/Gateways/Course.Gateway/*.csproj
COPY . . 
RUN dotnet publish Gateway/Gateways/Course.Gateway/*.csproj   -c Release -o out
FROM mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim as runtime

WORKDIR /app
COPY --from=build /app/out .
ENTRYPOINT ["dotnet","Course.Gateway.dll"]
 