version: '3.8'
services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
    - catalogdb_volume:/data/db
  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"
  discount:
    container_name: discountdb
    restart: always
    ports:
      - "5432:5432"
    volumes:
     - discount_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=discountdb
  identitydb:
    container_name: identitydb
    restart: always
    ports:
      - "1433:1433"
    volumes:
    - identity_volume:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y 
      - SA_PASSWORD=Serk@n1q2w3e4r!!  
  orderdb:
    container_name: orderdb
    restart: always
    ports:
      - "1444:1433"
    volumes:
     - orderdb_volume:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y 
      - SA_PASSWORD=Password12*
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
  catalog.api:
   container_name: catalog.api
   environment: 
   - ASPNETCORE_ENVIRONMENT=Development
   - RabbitMQUrl=rabbitmq
   - IdentityServerUrl:http://identityserver.api
   - DatabaseSettings:ConnectionString=mongodb://catalogdb:27017
   ports:
     - "5011:80"
   depends_on:
     - catalogdb
  identityserver.api:
   container_name: identityserver.api
   restart: on-failure
   environment: 
   - ASPNETCORE_ENVIRONMENT=Development
   - "ConnectionStrings:DefaultConnection=Server=identitydb,1433;Database=IdentityDB;User=sa;Password=Serk@n1q2w3e4r!!"
   ports:
     - "5001:80"
   depends_on:
     - identitydb    
   
  