version: '3.8'
services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
    - catalogdb_volume:/data/db
  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"
  discount:
    container_name: discountdb
    restart: always
    ports:
      - "5432:5432"
    volumes:
     - discount_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=discountdb
  identitydb:
    container_name: identitydb
    restart: always
    ports:
      - "1433:1433"
    volumes:
    - identity_volume:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y 
      - SA_PASSWORD=Serk@n1q2w3e4r!!  
  orderdb:
    container_name: orderdb
    restart: always
    ports:
      - "1444:1433"
    volumes:
     - orderdb_volume:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y 
      - SA_PASSWORD=Password12*
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
  catalog.api:
   container_name: catalog.api
   restart: on-failure
   environment: 
   - ASPNETCORE_ENVIRONMENT=Development
   - RabbitMQUrl=rabbitmq
   - IdentityServerUrl:http://identityserver.api
   - DatabaseSettings:ConnectionString=mongodb://catalogdb:27017
   ports:
     - "5011:80"
   depends_on:
     - catalogdb
  basket.api:

    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityServerUrl=http://identityserver.api
      - RedisSettings:Port=6379
      - RedisSettings:Host=basketdb

    ports:
      - "5013:80"
    depends_on:
      - basketdb
  photostock.api:
    container_name: photostock.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityServerUrl=http://identityserver.api
   

    ports:
      - "5012:80"
    volumes:
      - type: bind
        source: C:\Users\Sakca\OneDrive\Masaüstü/photos
        target: /app/wwwroot/photos
  discount.api:

    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityServerUrl=http://identityserver.api
      - "ConnectionStrings:PostgreSql=User ID= postgres;Password=123;Server=discountdb;Port=5432;Database=discountdb;Integrated Security=true;Pooling=true"

    ports:
      - "5014:80"
    depends_on:
      - discount  
  payment.api:
    container_name: payment.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityServerUrl=http://identityserver.api
      - RabbitMQUrl=rabbitmq
    ports:
      - "5016:80"
  order.api:
    container_name: order.api
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityServerUrl=http://identityserver.api
      - RabbitMQUrl=rabbitmq
      - "ConnectionStrings:DefaultConnection=Server=orderdb,1433;Database=SqlServer; User=sa; Password=Password12*"
      
    ports:
      - "5015:80"
    depends_on:
      - orderdb
  gateway.api:
    container_name: gateway.api
     
    environment:
      - ASPNETCORE_ENVIRONMENT=procution
      - IdentityServerUrl=http://identityserver.api
       
      
    ports:
      - "5000:80"
 
   
  identityserver.api:
   container_name: identityserver.api
   restart: on-failure
   environment: 
   - ASPNETCORE_ENVIRONMENT=Development
   - "ConnectionStrings:DefaultConnection=Server=identitydb,1433;Database=IdentityDB;User=sa;Password=Serk@n1q2w3e4r!!"
   ports:
     - "5001:80"
   depends_on:
     - identitydb    
   
  