FROM mcr.microsoft.com/dotnet/sdk:5.0-buster-slim as build
WORKDIR /app
EXPOSE 80
COPY Shared/Course.Shared/*.csproj Shared/Course.Shared/
COPY Services/PhotoStockl/Course.Services.PhotoStock/*.csproj Services/PhotoStockl/Course.Services.PhotoStock/
RUN dotnet restore Services/PhotoStockl/Course.Services.PhotoStock/*.csproj 
COPY . . 
RUN dotnet publish Services/PhotoStockl/Course.Services.PhotoStock/*.csproj -c Release -o out
FROM mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim as runtime

WORKDIR /app
COPY --from=build /app/out .
ENTRYPOINT [ "dotnet","Course.Services.PhotoStock.dll" ]
